### ISSUE TITLE
tox -e lint failing

### ISSUE THREAD

**Issue by dashmage** [canonical/prometheus-hardware-exporter#35]
`tox -e lint` fails while trying to install `pylint`.

```sh
 ❯ tox -e lint
lint: install_deps> python -I -m pip install black colorama flake8 flake8-colors flake8-docstrings isort mypy pep8-naming pylint pyproject-flake8 pytest pytest-cov -r /tmp/prometheus-hardware-exporter/requirements.txt -r /tmp/prometheus-hardware-exporter/tests/unit/requirements.txt -r /tmp/prometheus-hardware-exporter/tests/functional/requirements.txt
Collecting black
  Using cached black-23.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)

(...)

Collecting pylint
  Using cached pylint-0.27.0.tar.gz (224 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.26.0.tar.gz (222 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.25.2.tar.gz (214 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.25.1.tar.gz (211 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.25.0.tar.gz (205 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.24.0.tar.gz (203 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.23.0.tar.gz (200 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.22.0.tar.gz (232 kB)
  Preparing metadata (setup.py) ... done
  Using cached pylint-0.21.3.tar.gz (200 kB)
  Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-765nexfw/pylint_7f988c1308f944098948a83c628bc146/setup.py", line 111
          except OSError, ex:
                 ^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
lint: exit 1 (30.10 seconds) /tmp/prometheus-hardware-exporter> python -I -m pip install black colorama flake8 flake8-colors flake8-docstrings isort mypy pep8-naming pylint pyproject-flake8 pytest pytest-cov -r /tmp/prometheus-hardware-exporter/requirements.txt -r /tmp/prometheus-hardware-exporter/tests/unit/requirements.txt -r /tmp/prometheus-hardware-exporter/tests/functional/requirements.txt pid=299135
  lint: FAIL code 1 (30.25 seconds)
  evaluation failed :( (30.30 seconds)
```

**Comment by dashmage** [comment]
This was a temp issue I was facing on my local machine. After testing this again now, I don't see any issues. Closing the issue.
